### ISSUE TITLE
V3.26 "ERROR: cannot open (write)" for all recordings 

### ISSUE THREAD

**Issue by seansverige** [SquarePenguin101/forums.squarepenguin.co.uk#1]
I can't remember when I upgraded to 3.26, but I downloaded on the 10th so I assume then. Made recordings on the 10th, 13&14th, but subsequently all recordings have been failing with a message starting "ERROR: cannot open (write)" followed by details of the specific programme.

Checked my firewall, changed some settings, still failing
There aren't any advanced options to grant write access under Apps section of Windows settings
It's not unblocked list on Avast, but it's not blocked either- or in fact in it's list of apps at all
Both web PVR and command line fail with same error, and it's being by same user as ever - me - which has Admin rights.

Just reinstalled 3.23 - the previous version I was on - recording that was failing worked as normal.

Hardware W10 laptop, based in Ireland and use get_iplayer to download radio content only

BTW thanks for an excellent tool!

**Comment by josharcheruk** [comment]
You're in the wrong place. This is simply the repo for the archived forums that previously houses get_iplayer assistance. You won't get any help here. 

Try the mailing list: 

https://lists.infradead.org/mailman/listinfo/get_iplayer

Archive of mailing list here:

https://www.mail-archive.com/get_iplayer@lists.infradead.org/maillist.html

**Comment by SquarePenguin101** [comment]
Closing this issue as it is not about an issue with the repo content themselves.

**Comment by seansverige** [comment]
Will do - thanks for the info & apologies for the error
