### ISSUE TITLE
Category parsing

### ISSUE THREAD

**Issue by DarrenNewsgroup** [SquarePenguin101/forums.squarepenguin.co.uk#10]
I missed the use of "--category comedy" years ago in get_iplayer.
I was messing around with the Web PVR and noticed that categories field was populated rather than just blank,
I then did --info on a single pid and noticed that the info included categories field with values in it. Has the BBC re-added category and so could it be added back to get_iplayer (so I can download new comedy, not just programmes that I know the name of).
If the category is still not instantly available/searchable (like years ago) could I suggest an option that does a "--info .*" to download info about all programmes (to a new downloaded_history?) and this info is then searched (much like --history currently works) to find items with --category comedy and with --get download the new comedy.
I appreciate that this download might take a very long time (currently doing "get_iplayer --category comedy --history "infinite monkey" --info" is taking about 5 seconds per episode). I guess the download could be limited by use of --since 168 i.e. 1 week) but I don't mind a process on my PC taking this long as I would get the functionality back that I lost all those years ago.

**Comment by SquarePenguin101** [comment]
You’re in the wrong place - this is the repo for the archived forums. Go to the get-iplayer repo to raise an issue about get-iplayer.
