### ISSUE TITLE
Error when updating

### ISSUE THREAD

**Issue by KyleRickards** [SquarePenguin101/forums.squarepenguin.co.uk#2]
Hi

Before I mention anything else, can I just say thank you for all the work you have put into this. It is brilliant!

However, when I run a system update on Linux Mint 19.3, I get the following error message?

E: Failed to fetch http://ppa.launchpad.net/jon-hedgerows/get-iplayer/ubuntu/dists/bionic/InRelease  403  Forbidden [IP: 2001:67c:1560:8008::15 80]
E: The repository 'http://ppa.launchpad.net/jon-hedgerows/get-iplayer/ubuntu bionic InRelease' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.

Is there anything I can do? Am I asking in the right place?

Thank you
Kyle

**Comment by SquarePenguin101** [comment]
This is the issue tracker for the forum website. Not get_iplayer itself. Try the mailing list for help.
