### ISSUE TITLE
how to download tracklist from a series

### ISSUE THREAD

**Issue by AndyRubio** [SquarePenguin101/forums.squarepenguin.co.uk#3]
I use _gip b006tny5 --pid-recursive_ to download a series of radio programmes.

I want to also download the tracklist for each programme in the series, and from the docs assume I can use the form of _get_iplayer --tracklist --get 123_ to combine, eg:

get_iplayer --tracklist --get pid=b006tny5 --pid-recursive

but that doesn't work. Can anyone help?

**Comment by SquarePenguin101** [comment]
This is the issue tracker for the forum website. Not get_iplayer itself. Try the mailing list for help.
