### ISSUE TITLE
get_Iplayer not downloading HD Version of TV Series

### ISSUE THREAD

**Issue by PhilipLiv** [SquarePenguin101/forums.squarepenguin.co.uk#4]
Hi,

I tried to execute this:
get_iplayer --pid=m000qzkp --pid-recursive

and

get_iplayer --pid=b0072wk9 --pid-recursive

This is for the BBC Series **SPIRAL** _Season 8_ which is available in HD [here](https://www.bbc.co.uk/iplayer/episode/m000qzkp/spiral-series-8-episode-1)
But the download size is around 55MB - yes, FIFTY-FIVE MEGABYTES

This is a new issue, I haven't had this problem before
If I download it using the BBC iPlayer Downloads app in Windows 10, it downloads the HD version

what am I missing here?
thanks

**Comment by PhilipLiv** [comment]
btw, if I do this
get_iplayer --pid=m000qzkq --pid-recursive --**tvmode=best** 
then it downloads the HD version
so it's no longer default?

**Comment by DragonWolf5589** [comment]
i cant remember the command fully but i THINK its --options=tvmode=best (or something similar to that) then it makes it the option to try HD best quality mode by default. - I also added pid-recursive to the options so i never have to type that every time and it does it automatically

**Comment by DragonWolf5589** [comment]
sorry its --prefs-add i just checked the list of the commands in the software but the file saves to c:/users/NAME/.get_iplayer/options which you CAN do manually but its best through the command prompt

get_iplayer --prefs-add --tvmode=best

**Comment by SquarePenguin101** [comment]
This is the issue tracker for the forum website. Not get_iplayer itself. Try the mailing list for help.
