### ISSUE TITLE
edit prompt  and change  output folder

### ISSUE THREAD

**Issue by OAKIEDRIVER** [SquarePenguin101/forums.squarepenguin.co.uk#5]
Is there any way to edit it so when you open  you get **C:\users\Username get_iplayer** and not just C:\users\Username. It's a pain typing in the get_iplayer?

And can you change the output folder from the desktop?

**Comment by SquarePenguin101** [comment]
This is the issue tracker for the forum website. Not get_iplayer itself. Try the mailing list for help.
