### ISSUE TITLE
issue with "connecting to media server" 3.27.1

### ISSUE THREAD

**Issue by DragonWolf5589** [SquarePenguin101/forums.squarepenguin.co.uk#6]
Since I updated to 3.27.1 some reason even though im on a 500mbps line EVERYTHING i try to download stops about 20% downloaded, not going past 24mb/s then tells me 

WARNING: Unexpected size for file segment [10]
WARNING: Expected: 5679480  Downloaded: 1620918
WARNING: This indicates a problem with your network connection to the media server
WARNING: Retrying tv:

however it DOES eventually download them all fine on the 3rd attempt suddenly downloading past 200mb/s- but some reason it takes 3 attempts per episode, and it worked fine before this. - i have no issues with iplayer or my internet 

not sure whats happening or why,

**Comment by SquarePenguin101** [comment]
This is the issue tracker for the forum website. Not get_iplayer itself. Try the mailing list for help.
