### ISSUE TITLE
Relocate Get_Iplayer History file to another drive?

### ISSUE THREAD

**Issue by scuda2** [SquarePenguin101/forums.squarepenguin.co.uk#8]
After restoring a Windows system partition from a backup file, I notice that the get_iplayer history file does not have additions made since that backup..
I have searched the documentation for moving the history file to another location, with no success.
Would it be possible to consider a command to relocate the history file away from the Windows system partition? I'm sure I'm not the only one who would appreciate this.

regards,
Scuda2

**Comment by SquarePenguin101** [comment]
This is the repository for the archived forums. You're in the wrong place for feature requests. Go here: https://github.com/get-iplayer/get_iplayer/issues
