### ISSUE TITLE
tv recording quality isn't always the highest

### ISSUE THREAD

**Issue by 2dmartin** [SquarePenguin101/forums.squarepenguin.co.uk#9]
The wiki docs imply (say) that the default is to record at highest quality.  I *think* that's correct from the command line, but doesn't seem to be so for the web PVR.  Some PIDs do record at highest quality by default but check an episode of Repair Shop eg m0018kl6.  By default it isn't highest quality, and "fhd" is needed in the "Recording Quality" to force it.  A PID that does seem to record in highest quality in the PVR is the weekly weather video eg m0018shy.
Is the PVR broken or does what the Wiki says about default not apply to the PVR?

**Comment by SquarePenguin101** [comment]
You’re in the wrong place - this is the repo for the archived forums. Go to the get-iplayer repo to raise an issue about get-iplayer.
